### ISSUE TITLE
Dependency tree not flattening

### ISSUE THREAD

**Issue by tanepiper** [danmartinez101/babel-preset-react-hmre#15] opened 2016-02-18 13:47 UTC
Currently I'm about to enter the 7th ring of dependency hell....

I suspect this might be something more to do with NPM, but at this stage I've tried everything (installed NPM@2, dropped back to NPM@3.5, also the latest, cleaned the cache).

I did a clean out of the node_modules folder on a project I am working on locally, and since then I'm now getting this when running webpack dev server with `babel-preset-react-hmre`.

```
ERROR in ./src/containers/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' D:\Documents\GitHub\project\node_modules\babel-preset-react-hmre\node_modules\redbox-react\lib\index.js in D:\Documents\GitHub\project\src\containers
 @ ./src/containers/Root.js 27:13-155

ERROR in ./src/containers/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' D:\Documents\GitHub\project\node_modules\babel-preset-react-hmre\node_modules\react-transform-catch-errors\lib\index.js in D:\Documents\GitHub\project\src\containers
 @ ./src/containers/Root.js 31:14-172

ERROR in ./src/containers/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' D:\Documents\GitHub\project\node_modules\babel-preset-react-hmre\node_modules\react-transform-hmr\lib\index.js in D:\Documents\GitHub\project\src\containers
 @ ./src/containers/Root.js 39:14-163

ERROR in ./src/containers/Home.js
Module not found: Error: Cannot resolve 'file' or 'directory' D:\Documents\GitHub\project\node_modules\babel-preset-react-hmre\node_modules\redbox-react\lib\index.js in D:\Documents\GitHub\project\src\containers
 @ ./src/containers/Home.js 28:13-155

ERROR in ./src/containers/Home.js
Module not found: Error: Cannot resolve 'file' or 'directory' D:\Documents\GitHub\project\node_modules\babel-preset-react-hmre\node_modules\react-transform-catch-errors\lib\index.js in D:\Documents\GitHub\project\src\containers
 @ ./src/containers/Home.js 32:14-172

ERROR in ./src/containers/Home.js
Module not found: Error: Cannot resolve 'file' or 'directory' D:\Documents\GitHub\project\node_modules\babel-preset-react-hmre\node_modules\react-transform-hmr\lib\index.js in D:\Documents\GitHub\project\src\containers
 @ ./src/containers/Home.js 40:14-163
```

This happens with every file in my project that extends Component in React (so no actions, reducers, etc).  I've removed `redbox-react`, `react-transform-catch-errors` and `react-transform-hmr` as dependencies of my own project, but they are being installed in `node_modules` at the root of the directory - so they are in the tree - but still no luck.

Any help on this would be fantastic!

**Comment by SeeThruHead** [comment] 2016-02-18 14:10
I've encountered this when using react-hmre in a library. (For the example pages) react-hmre was set to be added in the 'development' environment. So when I published the lib (with env===development) react-hmre was added to all the files shipped with my lib, and would of course error out when using them in a consuming app.

**Comment by tanepiper** [comment] 2016-02-18 14:22
@SeeThruHead I don't think that's it.

For example I can quite happily build the project with `env === development`.  The only place it's used is in our `development_hot.js` config file:

```
webpackConfig.module.loaders.map(loader => {
  if (/js|jsx/.test(loader.test)) {
    loader.query.presets.push('react-hmre');
  }
});

webpackConfig.entry.app.push(
  `webpack-dev-server/client?${config.get('webpack_public_path')}`,
  `webpack/hot/dev-server`
);
```

I thought I'd try something there where I'd `unshift` rather than push it into the presets (which go in order `presets: ['es2015', 'react', 'stage-0']`) and got a different error:

```
ERROR in ./src/containers/Root.js
Module build failed: TypeError: D:/Documents/GitHub/project/src/containers/Root.js: Property value expected type of string but got function
    at Object.validate (D:\Documents\GitHub\project\node_modules\babel-types\lib\definitions\index.js:153:13)
    at validate (D:\Documents\GitHub\project\node_modules\babel-types\lib\index.js:269:9)
    at Object.builder (D:\Documents\GitHub\project\node_modules\babel-types\lib\index.js:222:7)
    at File.<anonymous> (D:\Documents\GitHub\project\node_modules\babel-core\lib\transformation\file\index.js:358:56)
    at File.addImport (D:\Documents\GitHub\project\node_modules\babel-core\lib\transformation\file\index.js:365:8)
    at D:\Documents\GitHub\project\node_modules\babel-plugin-react-transform\lib\index.js:257:46
    at Array.map (native)
    at ReactTransformBuilder.initTransformers (D:\Documents\GitHub\project\node_modules\babel-plugin-react-transform\lib\index.js:255:40)
    at ReactTransformBuilder.build (D:\Documents\GitHub\project\node_modules\babel-plugin-react-transform\lib\index.js:164:41)
    at PluginPass.Program (D:\Documents\GitHub\project\node_modules\babel-plugin-react-transform\lib\index.js:331:17)
    at newFn (D:\Documents\GitHub\project\node_modules\babel-traverse\lib\visitors.js:293:19)
    at NodePath._call (D:\Documents\GitHub\project\node_modules\babel-traverse\lib\path\context.js:74:18)
    at NodePath.call (D:\Documents\GitHub\project\node_modules\babel-traverse\lib\path\context.js:46:17)
    at NodePath.visit (D:\Documents\GitHub\project\node_modules\babel-traverse\lib\path\context.js:104:12)
    at TraversalContext.visitQueue (D:\Documents\GitHub\project\node_modules\babel-traverse\lib\context.js:156:16)
    at TraversalContext.visitSingle (D:\Documents\GitHub\project\node_modules\babel-traverse\lib\context.js:113:19)
    at TraversalContext.visit (D:\Documents\GitHub\project\node_modules\babel-traverse\lib\context.js:200:19)
 @ ./src/index.js 15:12-40
```

**Comment by danmartinez101** [comment] 2016-02-23 02:05
@tanepiper I've tried to get this to happen a couple of times with no success.

I would guess it has something to do with the use of `require.resolve('whatever')` calls in this preset. 
Would you be able to take a few minutes to create a reproduction repo or gist for this? I'd really like to resolve this for you and that will be easier with a repo.

**Comment by gaearon** [comment] 2016-03-06 02:58
I’d love to look into this but it’s impossible to help without seeing a project reliably reproducing the issue. (Side note: you may often discover the root of the issue while creating such a project.)

**Comment by jachenry** [comment] 2016-03-20 18:46
We resolved this issue by changing the presets order from:

`['es2015', 'react', 'stage-0', 'react-hmre']`

to:

`['react', 'es2015', 'stage-0', 'react-hmre']`

I can't explain why it worked or if its a reliable solution but it at least let us move forward.

**Comment by danmartinez101** [comment] 2016-03-22 00:40
@jachenry Thank you for sharing your experience :D
 
I'm going to close this for now. If this crops up again and can get a reproducible example, please feel free to re-open this issue.

**Closed by danmartinez101** 2016-03-22 00:40 UTC

**Comment by dogarfin** [comment] 2016-04-04 20:50
@jachenry Solution seemed to work for me as well. I ran into this problem with node 5.10 and npm 3.8.3

**Comment by huangbong** [comment] 2016-04-08 07:36
@jachenry Wow. Strange. Can also confirm that this solution worked for us as well. Thanks so much!

**Comment by geekyme** [comment] 2016-04-12 07:06
:+1: thanks the solution work but i have no idea why

**Comment by Yuliang-Lee** [comment] 2016-04-29 10:26
I encountered similar problems when babelrc is
```bash
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["antd"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }
}
```

if babelrc is 
```bash
{
  "presets": ["react", "es2015", "stage-0", "react-hmre"],
  "plugins": ["antd"],
  "env": {
    "development": {
      "presets": []
    }
  }
}
```
the problem disappeared. 
but I want to distinguish between production environment and development environment.
nodejs: v5.8.0
npm: v3.8.8

**Comment by tomaskulich** [comment] 2016-07-01 07:52
I ran into the same problem; it turns out that disabling webpack caching helps. Maybe rearanging presets order just make webpack to invalidate the cache?

**Comment by seanlindo** [comment] 2016-09-12 22:48
I'm running into this same problem now and it's only when this preset is enabled. Rearranging the presets didn't seem to help either. Is there something else it could be?
